/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carevnalebed;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author s153335
 */
public final class AnalyticsForm extends javax.swing.JFrame {

    /**
     * Creates new form AnalyticsForm
     */
    DefaultListModel<String> dlMiracles = null;
    DefaultListModel<String> dlPseudo   = null;
    DefaultListModel<String> dlTrash    = null;
    
    void ReloadTables() {
        dlMiracles.clear();
        dlPseudo.clear();
        dlTrash.clear();
        try {
            ResultSet rsMiracles = Globals.odbcConn.ExecuteQuery("SELECT * FROM CLMIRACLES");
            while(rsMiracles.next()) {
                dlMiracles.addElement(rsMiracles.getString("name"));
            }
            ResultSet rsPseudo = Globals.odbcConn.ExecuteQuery("SELECT * FROM CLPSEUDOMIRACLES");
            while(rsPseudo.next()) {
                dlPseudo.addElement(rsPseudo.getString("name"));
            }
            ResultSet rsTrash = Globals.odbcConn.ExecuteQuery("SELECT * FROM CLTRASH");
            while(rsTrash.next()) {
                dlTrash.addElement(rsTrash.getString("name"));
            }   
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public AnalyticsForm() {
            initComponents();
            this.setTitle("Меню аналитика");
            
            dlMiracles = new DefaultListModel<>();
            dlPseudo = new DefaultListModel<>();
            dlTrash = new DefaultListModel<>();
            
            jListMiracles.setModel(dlMiracles);
            jListPseudo.setModel(dlPseudo);
            jListTrash.setModel(dlTrash);
            
            ReloadTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPseudo = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMiracles = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTrash = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jExit = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Каталог псевдочудес");

        jListPseudo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPseudoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListPseudo);

        jListMiracles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMiraclesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListMiracles);

        jLabel2.setText("Каталог чудес");

        jListTrash.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTrashValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListTrash);

        jLabel3.setText("Корзина");

        jLabel4.setText("Описание");

        jTextDescription.setColumns(20);
        jTextDescription.setRows(5);
        jTextDescription.setEnabled(false);
        jScrollPane4.setViewportView(jTextDescription);

        jButton1.setText("Утвердить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("В корзину");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("В корзину");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("В чудеса");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jExit.setText("Выход");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                        .addComponent(jExit)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jExit))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        Globals.odbcConn.Logout();
        this.setVisible(false);
        Globals.MainFormLogin.setVisible(true);
    }//GEN-LAST:event_jExitActionPerformed

    private void jListPseudoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPseudoValueChanged
        try {
            ResultSet rs = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+ (String)jListPseudo.getSelectedValue()+"'");
            if(rs.next())
                jTextDescription.setText(rs.getString("description"));
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jListPseudoValueChanged

    private void jListMiraclesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMiraclesValueChanged
        try {
            ResultSet rs = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLMIRACLES\" WHERE \"name\"='"+ (String)jListMiracles.getSelectedValue()+"'");
            if(rs.next())
                jTextDescription.setText(rs.getString("description"));
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListMiraclesValueChanged

    private void jListTrashValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTrashValueChanged
        try {
            ResultSet rs = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLTRASH\" WHERE \"name\"='"+ (String)jListTrash.getSelectedValue()+"'");
            if(rs.next())
                jTextDescription.setText(rs.getString("description"));
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListTrashValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ResultSet rsSrc = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+ (String)jListPseudo.getSelectedValue()+"'");
            if(rsSrc.next()) {
                String name = rsSrc.getString("name");
                String desc = rsSrc.getString("description");
                ResultSet rsDelete = Globals.odbcConn.ExecuteQuery("DELETE FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+name+"'");
                ResultSet rsDst = Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLMIRACLES\" (\"name\", \"description\") VALUES ('"+name+"', '"+desc+"')");
                dlPseudo.removeElement(name);
                dlMiracles.addElement(name);
                
                ReloadTables();
                //INSERT INTO "S153335"."CLMIRACLES" ("name", "description") VALUES ('gg', 'hhh') RETURNING ROWID INTO :NAV_ROWID
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ResultSet rsSrc = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+ (String)jListPseudo.getSelectedValue()+"'");
            if(rsSrc.next()) {
                String name = rsSrc.getString("name");
                String desc = rsSrc.getString("description");
                ResultSet rsDelete = Globals.odbcConn.ExecuteQuery("DELETE FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+name+"'");
                ResultSet rsDst = Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLTRASH\" (\"name\", \"description\") VALUES ('"+name+"', '"+desc+"')");
                dlPseudo.removeElement(name);
                dlTrash.addElement(name);
                
                ReloadTables();
                
                //INSERT INTO "S153335"."CLMIRACLES" ("name", "description") VALUES ('gg', 'hhh') RETURNING ROWID INTO :NAV_ROWID
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            ResultSet rsSrc = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLMIRACLES\" WHERE \"name\"='"+ (String)jListMiracles.getSelectedValue()+"'");
            if(rsSrc.next()) {
                String name = rsSrc.getString("name");
                String desc = rsSrc.getString("description");
                ResultSet rsDelete = Globals.odbcConn.ExecuteQuery("DELETE FROM \"S153335\".\"CLMIRACLES\" WHERE \"name\"='"+name+"'");
                ResultSet rsDst = Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLTRASH\" (\"name\", \"description\") VALUES ('"+name+"', '"+desc+"')");
                dlMiracles.removeElement(name);
                dlTrash.addElement(name);
                
                ReloadTables();
                //INSERT INTO "S153335"."CLMIRACLES" ("name", "description") VALUES ('gg', 'hhh') RETURNING ROWID INTO :NAV_ROWID
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            ResultSet rsSrc = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLTRASH\" WHERE \"name\"='"+ (String)jListTrash.getSelectedValue()+"'");
            if(rsSrc.next()) {
                String name = rsSrc.getString("name");
                String desc = rsSrc.getString("description");
                ResultSet rsDelete = Globals.odbcConn.ExecuteQuery("DELETE FROM \"S153335\".\"CLTRASH\" WHERE \"name\"='"+name+"'");
                ResultSet rsDst = Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLMIRACLES\" (\"name\", \"description\") VALUES ('"+name+"', '"+desc+"')");
                dlTrash.removeElement(name);
                dlMiracles.addElement(name);
                //INSERT INTO "S153335"."CLMIRACLES" ("name", "description") VALUES ('gg', 'hhh') RETURNING ROWID INTO :NAV_ROWID
                ReloadTables();
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnalyticsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Globals.odbcConn.Logout();
        this.setVisible(false);
        Globals.MainFormLogin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyticsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListMiracles;
    private javax.swing.JList jListPseudo;
    private javax.swing.JList jListTrash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextDescription;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
