/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carevnalebed;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/**
 *
 * @author s153335
 */
public class AssemblerForm extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form AssemblerForm
     */
    DefaultListModel<String> dlPseudomiracles = null;
    
    void ReloadTables() {
        try {
            dlPseudomiracles.clear();
            
            ResultSet rsMircs = Globals.odbcConn.ExecuteQuery("SELECT * FROM CLPSEUDOMIRACLES");
            while(rsMircs.next()) {
                dlPseudomiracles.addElement(rsMircs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AssemblerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public AssemblerForm() {
            initComponents();
            this.setTitle("Меню корабельщика(сборщика)");
            dlPseudomiracles = new DefaultListModel<>();
            dlPseudomiracles.clear();
            jListMiracles.setModel(dlPseudomiracles);
            
            ReloadTables();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNameMir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescription = new javax.swing.JTextPane();
        jButtonRegister = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMiracles = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Зарегистрировать чудо на рассмотрение");

        jLabel2.setText("Чудо:");

        jLabel3.setText("Описание:");

        jScrollPane1.setViewportView(jTextPaneDescription);

        jButtonRegister.setText("Регистрация");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListMiracles);

        jLabel4.setText("Чудеса:");

        jExit.setText("Выход");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(36, 36, 36)
                                    .addComponent(jTextNameMir))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jExit)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jExit))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNameMir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegister))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        try {
            jLabelMessage.setText("");
            if(jTextNameMir.getText().length()==0) {
                jLabelMessage.setText("Введите название чуда");
                return;
            }
            if(jTextPaneDescription.getText().length()==0) {
                jLabelMessage.setText("Опишите чудо");
                return;
            }
            
            //поиск по корзине
            ResultSet rsTrash = Globals.odbcConn.ExecuteQuery("SELECT COUNT(*) FROM \"S153335\".\"CLTRASH\" WHERE \"name\"='"+ jTextNameMir.getText() +"'");
            rsTrash.next();
            if(rsTrash.getInt(1)!=0) {
                jLabelMessage.setText("Чудо было признано недееспособным");
                return;
            }
          
            //поиск по каталогу чудес
            ResultSet rsMircs = Globals.odbcConn.ExecuteQuery("SELECT COUNT(*) FROM \"S153335\".\"CLMIRACLES\" WHERE \"name\"='"+ jTextNameMir.getText() +"'");
            rsMircs.next();
            if(rsMircs.getInt(1)!=0) {
                jLabelMessage.setText("Чудо уже признано чудом");
                return;
            }
            
            //не существует ли в каталоге псевдочудес 
            ResultSet rsPseudo = Globals.odbcConn.ExecuteQuery("SELECT COUNT(*) FROM \"S153335\".\"CLPSEUDOMIRACLES\" WHERE \"name\"='"+ jTextNameMir.getText() +"'");
            rsPseudo.next();
            if(rsPseudo.getInt(1)!=0) {
                jLabelMessage.setText("Псевдочудо уже существует в списке");
                return;
            }            

    //INSERT INTO "S153335"."CLPSEUDOMIRACLES" ("name", "description") VALUES ('какашка', 'просто какашка') RETURNING ROWID INTO :NAV_ROWID        
            //добавление чуда
            ResultSet rsAdd = Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLPSEUDOMIRACLES\" (\"name\", \"description\") VALUES ('"+jTextNameMir.getText()+"', '"+jTextPaneDescription.getText()+"')");
            jLabelMessage.setText("Псевдочудо добавлено в список");
            dlPseudomiracles.addElement(jTextNameMir.getText());
        } catch (SQLException ex) {
            Logger.getLogger(AssemblerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ReloadTables();
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        Globals.odbcConn.Logout();
        this.setVisible(false);
        Globals.MainFormLogin.setVisible(true);
    }//GEN-LAST:event_jExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssemblerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssemblerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssemblerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssemblerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssemblerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JList jListMiracles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextNameMir;
    private javax.swing.JTextPane jTextPaneDescription;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
