/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carevnalebed;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author s153335
 */
public final class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    static int userId = 0;
    DefaultListModel<String> dlMiracles = null;
    DefaultListModel<String> dlWishes   = null;
    
    void ReloadTables() {
        try {
            dlMiracles.clear();
            dlWishes.clear();
            
            ResultSet rsMir = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLMIRACLES\"");
            while(rsMir.next()) {
                dlMiracles.addElement(rsMir.getString("name"));
            }
            ResultSet rsWishes = Globals.odbcConn.ExecuteQuery("SELECT * FROM \"S153335\".\"CLORDERS\" WHERE \"id_user\"='" +userId+ "'");
            while(rsWishes.next()) {
                dlWishes.addElement( Globals.odbcConn.GetMiracleNameById(rsWishes.getInt("id_miracle")) );
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public UserForm(int uid) {
            initComponents();
            this.setTitle("Личный кабинет пользователя");
            userId = uid;
            System.out.println("client ID = " + userId);
            
            dlMiracles = new DefaultListModel<>();
            dlWishes = new DefaultListModel<>();
            jListMiracles.setModel(dlMiracles);
            jListWishes.setModel(dlWishes);
            
            ReloadTables();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMiracles = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListWishes = new javax.swing.JList();
        jBUttonWant = new javax.swing.JButton();
        jButtonDontWant = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Каталог чудес:");

        jScrollPane1.setViewportView(jListMiracles);

        jLabel2.setText("Каталог желаний:");

        jScrollPane2.setViewportView(jListWishes);

        jBUttonWant.setText("Хочу");
        jBUttonWant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUttonWantActionPerformed(evt);
            }
        });

        jButtonDontWant.setText("Больше не хочу");
        jButtonDontWant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDontWantActionPerformed(evt);
            }
        });

        jLabel3.setText("Внимание: удаленные заказы возврату не подлежат");

        jButtonExit.setText("Выход");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBUttonWant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDontWant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButtonExit))
                        .addGap(301, 301, 301))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBUttonWant)
                    .addComponent(jButtonDontWant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        Globals.odbcConn.Logout();
        this.setVisible(false);
        Globals.MainFormLogin.setVisible(true);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jBUttonWantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUttonWantActionPerformed
        String item = (String)jListMiracles.getSelectedValue();

            for(Object o:dlWishes.toArray()) {
                String tmp = (String)o;
                if(item.equals(tmp)) return;
            }
                Globals.odbcConn.ExecuteQuery("INSERT INTO \"S153335\".\"CLORDERS\" (\"id_miracle\", \"id_user\") VALUES ('"+Globals.odbcConn.GetMiracleIdByName(item)+"', '"+userId+"')");
                dlWishes.addElement(item);
        ReloadTables();
    }//GEN-LAST:event_jBUttonWantActionPerformed

    private void jButtonDontWantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDontWantActionPerformed
        Globals.odbcConn.ExecuteQuery("DELETE FROM \"S153335\".\"CLORDERS\" WHERE \"id_miracle\"='"+ Globals.odbcConn.GetMiracleIdByName((String)jListWishes.getSelectedValue()) +"'");
        dlWishes.removeElement(jListWishes.getSelectedValue());
        ReloadTables();
    }//GEN-LAST:event_jButtonDontWantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBUttonWant;
    private javax.swing.JButton jButtonDontWant;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListMiracles;
    private javax.swing.JList jListWishes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
